spring:
  datasource:
    url: jdbc:h2:mem:recipe
    username: recipe-project
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false